### ISSUE TITLE
Создать документацию UserViewSet

### ISSUE THREAD

**Issue by levozavr** [robot-lab/judyst-main-web-service#108]
# Code maintenance request

## Опишите проблему, которая приводит к необходимости этих изменений

Надо создать документацию для объекта UserViewSet
На основании feature #43 

## Дополнительные материалы
- [x] [UserViewSet](https://github.com/robot-lab/judyst-main-web-service/blob/tasks-10-16-19-30/core/views.py)

**Comment by Vasar007** [comment]
На данный момент задача решена.
