### ISSUE TITLE
Сделать внешнюю документацию для модуля авторизации

### ISSUE THREAD

**Issue by danila19991** [robot-lab/judyst-main-web-service#11]
# Task request

## Цель задачи

Сделать документацию к модулю авторизации пользователей, на основе требований из task #9 
Необходима для: feature #4, feature #5, feature #6, feature #7.

## Решение задачи

Таблица со списком примеров положительных и негативных результатов для определенных запросов на некоторые url в соответствии с проведенной аналитикой(документация для последующего написания тестов по стратегии "черный ящик").

**Comment by Vasar007** [comment]
@danila19991, в каком смысле не согласовано?

**Comment by danila19991** [comment]
@Vasar007, Лева еще не просмотрел(может я там что-то не так написал).

**Comment by Vasar007** [comment]
@danila19991, тогда просим @levozavr принять участие в решении данной задачи.

**Comment by levozavr** [comment]
@danila19991 @Vasar007 изменения внесены в [это](https://docs.google.com/spreadsheets/d/1ILDIR0_LEIYinvhQHQs-mMdu03_QqHtoJjJKVxAH-nY/edit#gid=0)
@danila19991 ты со всем согласен?

**Comment by Vasar007** [comment]
Для решения таких вопросов, которые мне показывал Лев, не нужен именно бизнес-аналитик. Они решаются разработчиками, потому что данные вопросы относятся не к пользователям, а к конкретным сценариям поведения системы при определённых действиях, что и в данном случае это является деталью реализации.

**Comment by levozavr** [comment]
@danila19991 нет, пока, она передана тестировщику на тестирование документации

**Comment by Kn1MS** [comment]
@levozavr, эту заметку стоило добавить к моему issue про тестирование документации. Информации много, упустить просто. Я просто подумал, что это надо будет тестировать на настоящие баги уже при наличии кода.

**Comment by danila19991** [comment]
необходимые изменения для данного issue указаны в #43

**Comment by Vasar007** [comment]
Перенос работ на задачу #43.
