### ISSUE TITLE
Проведение тестирования технической документации

### ISSUE THREAD

**Issue by Kn1MS** [robot-lab/judyst-main-web-service#12]
# Idea proposal
Провести анализ технической документации, чтобы избежать проблем с разночтениями по ней в будущем.

## В чём заключается идея
Идея заключается в том, что тестировщик, на текущий момент свободный от необходимости работать с кодом, может провести предварительное тестирование основной документации. В основном посредством детального просмотра документов и обсуждения спорных или кажущихся неверными моментов с другими членами команды.

**Comment by Kn1MS** [comment]
Была проведена инспекция ТЗ, в ходе которой оказался выявлен ряд проблем, в основном связанных с неоднозначностью и простотой восприятия требований. Также было указано на некоторые незавершённые моменты (один из которых, например, касался отсутствующей части о форме учётной записи пользователя) . Тестировщик Зыков А. Ю. отметил всё обнаруженное в виде комментариев к google-документу. В ходе работы над исправлением ошибок указанные проблемы были решены.

**Comment by danila19991** [comment]
@Kn1MS, нужно разбить на задачи

**Comment by Vasar007** [comment]
@Kn1MS, такую аналитику мы оставляем на уровне идей. Ведь именно с аналитикой мы и работаем в данном случае.

**Comment by Vasar007** [comment]
Потому что при разбиении мы просто получим дублирование, что плохо.

**Comment by Kn1MS** [comment]
Всё пофиксили, закрываю.
