### ISSUE TITLE
Обновление таблицы кодексов и документов

### ISSUE THREAD

**Issue by danila19991** [robot-lab/judyst-main-web-service#126]
# Task request

## Цель задачи

Собрать требования от коллег и выяснить цель задачи. В зависимости от требований обновить функциональность.
На основании idea #124 

## Решение задачи

Список полей для таблицы кодексов, и описание механизма взаимодействия; Таблица с этими полями в коде

**Comment by danila19991** [comment]
@mehwhatever0, я ведь правильно понял что нужны следующие поля: supertype, doc_type, absolute_path, title, release_date, text_source_url, effective_date, cons_selected_info, text, interredation_id  
Возможно вынести cons_selected_info в отдельную таблицу

Какой механизм взаимодействия с этой таблицей нужен?

**Comment by navolotsky** [comment]
@danila19991, да. 
Старые поля: doc_id, supertype, doc_type, title, release_date, text, text_source_url.

плюс 
Новые поля: effective_date, absolute_path, interredaction_id, cons_selected_info. 

Что касается cons_selected_info, то я не знаю, как лучше сделать. По сути он содержит важную дополнительную инфу, которую фронт будет показывать пользователю о конкретном положении кодекса. Я не знаю, как вам удобнее будет это организовать.

**Comment by navolotsky** [comment]
@danila19991, на всякий случай полный перечень возможных подполей в cons_selected_info:

Данная информация должна быть полезна фронту, @Rexarrior.

Целые числа:

- rd_number — порядковый номер редакции, указан только у самой редакции
- prev_rd_doc_num — номер документа предыдущей редакции, указан только у самой редакции
- rd_doc_number — номер документа редакции, указан у всех положений редакции
- intext_label — внутренний номер данного положения редакции в тексте документа редакции на КонсультантПлюс

Строки:
1) Указаны только у самой редакции:

- rd_type — тип редакции
- rd_description — описание редакции
- unicode_text_link — ссылка, по которой можно скачать текст редакции в unicode
- reference_info — html со справкой к редакции с КонсультантПлюс
- changes_review_link — ссылка на обзор изменений, вносимых редакцией.

2) Первые три есть у всех положений редакции, последние два могут как присутствовать, так и отсутствовать у разных положений редакции:
- rd_doc_link — ссылка на положение в данной редакции на КонсультантПлюс
- redaction_comparison_link — ссылка на сравнение с предыдущей редакцией данного положения на КонсультантПлюс
- addit_info_link — ссылка на дополнительную информацию о положении
- redaction_note — примечание о редакции данного положения
- cons_note — примечание Консультанта к данному положению

Json-структуры

- attached_titles — список строк, заголовки к данному положению, начиная от заголовка кодекса и до заголовка данного положения (возможно, пригодится  **_при поиске положений пользователем_** по их заголовкам)

![image](https://user-images.githubusercontent.com/43314216/48913071-6a3ac700-ee88-11e8-9c62-b2bf77e04f4c.png)

- redactions - список словарей, информация о редакциях; есть только у самого кодекса

![image](https://user-images.githubusercontent.com/43314216/48913076-6dce4e00-ee88-11e8-82e3-3bb309274eaf.png)

**Comment by Rexarrior** [comment]
Документы загружены в таблицу на проде. Веб краулер обновлен для работы с новыми типами документов.

**Comment by danila19991** [comment]
closed in #127
