### ISSUE TITLE
500 при запросе документа

### ISSUE THREAD

**Issue by Rexarrior** [robot-lab/judyst-main-web-service#129]
# Bug report

## Описание ошибки
Страницы с текстами документов не открываются. Причина - 500 server internal error

## Воспроизводение ошибки
http://68.183.66.108:8000/#/document/АС_ТЕСТ_А79-9231_2016/0
## Ожидаемое поведение
Должен отобразиться текст. В консоле не должно быть ошибок. (ответ сервера 200) 
## Скриншоты | логи
![image](https://user-images.githubusercontent.com/25753287/49030317-0da51800-f1b8-11e8-87c8-b78577516304.png)

**Comment by levkovalenko** [comment]
![image](https://user-images.githubusercontent.com/30433199/49037072-61b8f800-f1ca-11e8-980e-d006efbb3e02.png)
Лог ошибки на стороне сервера

**Comment by Rexarrior** [comment]
Починил. Причина была в том, что неверно обрабатывался id на фронте. Соответственно, на сервер уходил несуществующий doc_id. 
Теперь вылезла проблема с не совсем верным наполнением текста - туда каким-то образом улетел json, окружающий текст. 
Нужно перезалить тексты AC_TEST.

**Comment by Rexarrior** [comment]
Выдачу документов починил путем перезаливки текстов в корректном виде.
Осталось сделать ответ 404 на запрос несуществующего документа вместо текущего 500.
