### ISSUE TITLE
Создание таблицы трассировки для тестов

### ISSUE THREAD

**Issue by Kn1MS** [robot-lab/judyst-main-web-service#130]
# Task request

## Цель задачи

Необходимо создать таблицу трассировки тестов для оценки покрытия кода тестами.

## Решение задачи

Использовать гугл-таблицы и имеющуюся документацию + код.

## Дополнительный контекст или ссылки на связанные с данной задачей issues

Отсутствует.

**Comment by Kn1MS** [comment]
Таблица закончена, ожидаю одобрения со стороны других людей:
@Vasar007 
@levozavr

**Comment by levkovalenko** [comment]
@Kn1MS подтверждаю что задача закончена

**Comment by Vasar007** [comment]
+

**Comment by Kn1MS** [comment]
Ссылка на текущий вариант:
[Тык](https://docs.google.com/spreadsheets/d/1Jf6CXSr3W0JI_5zf9W61EyBIm55ssK7xoh39qx820V8/edit#gid=0)

При необходимости дополнения можно будет либо это issue переоткрывать, либо новое создавать. Пока закрываю.
