### ISSUE TITLE
Создание окружения

### ISSUE THREAD

**Issue by levozavr** [robot-lab/judyst-main-web-service#23]
# Feature request

## Почему Вы заинтересованы в данном функционале

Это поможет сократить время на развертку системы на новой машине, так же упростит задачу разработчикам и тестировщикам создания локального окружения с одинаковой версионностью инструментов. В будущем это упростит процесс CI-CD и deploy 
На основании idea #8 

## Функционал, который Вы хотите

Docker контейнер с набором необходимых инструментов. Docker container с поддержкой возможности сборки системы.

## Как Вы будете использовать этот функционал

Развертка docker контейнера для проведения тестирования системы или ее компоненты, а так же для debugging'а кода. В будущем процедура CI-CD и Deploy

## Кому будет интересен данный функционал

Developers, Testers, DevOps 

## Дополнительный контекст или ссылки на связанные с данной задачей issues

- [x] task #24 
- [x] task #25

**Comment by danila19991** [comment]
Все задачи связанные с этой функциональностью сделаны.
