### ISSUE TITLE
Сoздать контейнер с внешним окружением

### ISSUE THREAD

**Issue by levozavr** [robot-lab/judyst-main-web-service#24]
# Task request

## Цель задачи

Создать docker со всеми необходимыми инструментами для работы системы.
feature #23 

## Решение задачи

Docker container на Debian со следующими инструментами

- [x] Postrgers sql
- [x] RabbitMq / Redis

Добавьте любой другой контекст, связанный с задачей.

**Comment by levozavr** [comment]
https://hub.docker.com/r/qio0/rmq_psql/
по данной ссылку доступен контейнер с внешним окружением

**Comment by danila19991** [comment]
Контейнер содержит настроенное внешнее окружение необходимое для разработки.
