### ISSUE TITLE
Создать контейнер с внутренни окружением

### ISSUE THREAD

**Issue by levozavr** [robot-lab/judyst-main-web-service#25]
# Task request

## Цель задачи

Для упрощения дальнейшей процедуры CI/CD создать контейнер с python3
feature #23
 
## Решение задачи

Созадть docker container на debian со следующими инструменатми

- [x] python3

**Comment by danila19991** [comment]
ссылка на репозиторий с контейнером: https://hub.docker.com/r/colosus/gitnud-repository-starter/
