### ISSUE TITLE
Настройка проекта

### ISSUE THREAD

**Issue by levozavr** [robot-lab/judyst-main-web-service#26]
# Feature request

## Почему Вы заинтересованы в данном функционале

Это необходимо для того что бы приступить непосредственно к разработке webservice нашей системы. 
На основании idea  #8

## Функционал, который Вы хотите

Я хочу CI-CD, codefactor, заготовку django проекта

## Как Вы будете использовать этот функционал

Он будет применим во время разработки, будет  упрощать проверку задач. 

## Кому будет интересен данный функционал

@levozavr @danila19991 

## Дополнительный контекст или ссылки на связанные с данной задачей issues

- [x] task #27 
- [x] task #28 
- [ ] task #83

**Comment by danila19991** [comment]
Closed in #31

**Comment by danila19991** [comment]
Все задачи связанные с этой функциональностью выполнены
