### ISSUE TITLE
Создание модели пользователя

### ISSUE THREAD

**Issue by danila19991** [robot-lab/judyst-main-web-service#4]
# Feature request

## Почему Вы заинтересованы в данном функционале

Требуется хранить некоторые данные о пользователях. В частность email, password.
На основании idea #1 

## Функционал, который Вы хотите

Django модель, расширяющуюся стандартную модель пользователя.

## Как Вы будете использовать этот функционал

Подтверждать пользователя через сочетание email, password. Восстанавливать доступ к аккаунту через список указанных при регистрации email.

## Дополнительный контекст или ссылки на связанные с данной задачей issues

Текущий список требований для пользователя: [тык](https://docs.google.com/document/d/1vnavh7tkKxfvMN32qlIEy7BUbqQOD9zVBy1OhkKIG9U/edit)

- [x] task #9 
- [x] task #10

**Comment by Vasar007** [comment]
@danila19991, необходимо обновить список обязательных для пользователя полей, которые я тебе присылал. Также добавь указание про необязательные поля в учётной записи пользователя.

**Comment by Vasar007** [comment]
Ок, теперь всё нормально.

**Comment by danila19991** [comment]
Все подзадачи решены
