### ISSUE TITLE
Создание test suit для авторизации пользователей

### ISSUE THREAD

**Issue by danila19991** [robot-lab/judyst-main-web-service#43]
# Task request

## Цель задачи

Создать test suit по модулю "авторизация пользователя".
На основании idea #1 и idea #32 

## Решение задачи

Test suit в виде google doc согласно регламенту.

## Дополнительный контекст или ссылки на связанные с данной задачей issues

Данная функциональность не разбита полностью.

Под задачи:
- [x] task #108

**Comment by Kn1MS** [comment]
@levozavr, ты упоминал, что таблица для API в доках устарела. Её обновить надо?

**Comment by Vasar007** [comment]
@levozavr, @Kn1MS, каков статус текущей задачи?

**Comment by danila19991** [comment]
https://docs.google.com/spreadsheets/d/1TwXh-fOf89D3iHtFOlMh5tMvvC5Vx_njND55B0Gmxtc/edit#gid=0
