### ISSUE TITLE
Создание проекта и настройка окружения

### ISSUE THREAD

**Issue by danila19991** [robot-lab/judyst-main-web-service#8]
# Idea proposal

## В чём заключается идея

Создать проект и настроить окружение для него.

## Возможное решение

Докер образ контейнера с окружением для запуска web сервиса.

## Дополнительный контекст или ссылки на связанные с данной задачей issues

- [x] feature #23 
- [x] feature #26

**Comment by levozavr** [comment]
@danila19991 какое окружение нам надо?
- [ ] debian
- [ ] postgres sql
- [ ] rabbitMQ
- [ ] redis
я все указал?

**Comment by danila19991** [comment]
@levozavr, pythom, библиотеки для python

**Comment by levozavr** [comment]
@danila19991  если я правильно понял то docker образ будет содержать внешнее окружения без самого проекта, проект же будет разрабатываться локально

**Comment by levozavr** [comment]
@danila19991 нам понадобится ещё один контейнер

- [ ] debian
- [ ] python3

**Comment by danila19991** [comment]
Все функциональности связанные с этой идеей выполнены.
