### ISSUE TITLE
Доставка статики для сайта

### ISSUE THREAD

**Issue by danila19991** [robot-lab/judyst-main-web-service#85]
# Feature request

## Почему Вы заинтересованы в данном функционале

Нужно как-то загружать сайт на сторону клиента.

## Функционал, который Вы хотите

Передача файлов сайта в браузер пользователя.

## Как Вы будете использовать этот функционал

Пользователь будет использовать нашу систему.

## Кому будет интересен данный функционал

Пользователю

**Comment by danila19991** [comment]
@levozavr, как будем сайт раздавать?

**Comment by Rexarrior** [comment]
Все успешно раздается через django.
