### ISSUE TITLE
Аналитика по нужным пользователям параметрам

### ISSUE THREAD

**Issue by danila19991** [robot-lab/judyst-main-web-service#9]
# Task request

## Цель задачи

Провести аналитику по необходимым полям для модели пользователя. Получим требования для task #10.
На основании feature #4.

## Решение задачи

Список полей необходимых для модели пользователя.

**Comment by Vasar007** [comment]
Закрываю данную задачу до тех пор, пока не будет необходимости в проведении дополнительной аналитики по пользователям.
